name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Hello
      run: echo 'Hello World'

    - name: Testing
      run: |
        curl -I https://gyanavardhana.github.io/hva-coursepage/ > output.txt
        if grep -q 'HTTP/2 200' output.txt; then
          echo 'The status code is 200 OK'
        else
          echo 'The status code is not 200 OK'
          exit 1  # This line stops the workflow if the test fails
        fi

  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Clean up
      run: echo 'bye bye task done'
